// <auto-generated />
namespace Mikes_Bikes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adminfieldincustomertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adminfieldincustomertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281350336_Admin field in customer table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
