// <auto-generated />
namespace Mikes_Bikes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class forgot_some_requires : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forgot_some_requires));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231355501_forgot_some_requires"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
